[dependencies]
base = "0.14.6"
new-base = "0.3.0"

[package]
name = "asn1"
version = "0.0.1"
description = ""
repository = "https://github.com/edjcase/motoko_asn1"
keywords = [ "ASN.1", "ASN1", "DER", "encode", "decode" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
